{% set name = "synthatdelays" %}
{% set version = "1.0.1" %}
{% set python_min = "3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/synthatdelays-{{ version }}.tar.gz
  sha256: 77410bc310720ae475325e579759d6089d653a48958fa966738a96f064a78134

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77.0.3
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.0.0
    - statsmodels

test:
  imports:
    - synthatdelays
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A library with a minimal model of operations between airports, designed to synthesise realistic time series of delays and operations.
  license: AGPL-3.0-only
  license_file: LICENSE
  home: https://gitlab.com/MZanin/synth-at-delays
  doc_url: https://gitlab.com/MZanin/synth-at-delays/-/wikis/home
  dev_url: https://gitlab.com/MZanin/synth-at-delays

extra:
  recipe-maintainers:
    - DrMZanin
    - cbueth
